### ISSUE TITLE
Tabhunter popup is blank and transparent (just a border)

### ISSUE THREAD

**Issue by reikred** [ericpromislow/tabhunter#105] opened 2020-04-11 18:06 UTC
Discovered after after switching to firefox-75.0 (linux) and updated tabhunter "version": "3.0.5", but may not be related to the switch nor updated TH.

In profile called VV, tabhunter does not work. When TH icon clicked, TH pops up a window with nothing in it (transparent, just a border). At the same time, an F12.console will print the eror message

CONSOLE: "Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8"

In another profile AA, tabhunter DOES work (TH icon pops  a window one can search in), and the aforementioned error message does NOT occur, which I therefore think may be relevant to the problem.

Related side-question: How much data does TH store? Is it "safe" to uninstall/reinstall in attempt to fix the subject problem, meaning no data loss?

**Comment by ericpromislow** [comment] 2020-04-11 18:24
tabhunter doesn't store much data -- your last search and a few prefs, like whether to show tabs by alpha, window/tab order, or by neglect. So reinstalling should not cause you too much grief.

I don't know why Tabhunter should trigger an error message involving nsIFile. Maybe when it's trying to show a local tab's favicon. Hmmm, that might be the cause of it. Do you feel like hacking the code a bit so you can get an exception object and show where exactly that's happening?

**Comment by reikred** [comment] 2020-04-11 18:58
The buggy behavior does not depend on whether a favicon is visible on the tab. It is the same on all tabs.

My javascript skills are almost nonexistent. My somewhat detailed bug description is mostly due to an innate desire to describe the bug as well as I can.

**Comment by reikred** [comment] 2020-04-11 19:04
A convoluted sequence that made TH work again: Remove, exit, restart, installTH, exit, restart.

That is, if I remember the sequencwe correctly. Does not seem right though that one should have to go through such gyrations.

**Comment by ericpromislow** [comment] 2020-04-11 21:11
Good to hear that you figured it out. Also good to hear that there are other uses for Tabhunter besides keeping 80 different pages of online programming references in separate tabs.

**Comment by reikred** [comment] 2020-05-18 02:12
Hmm, this problem (blank TH window)  keeps happening, and it appears to be coincident with the cache being full (see Cookies and Site Data under the URL about:preferences#privacy). If you clear site data and then restart firefox, the problem goes away, but just restart does not work.

I think the bug is that TH pops its window, then starts writing something to cache and then gets stuck because the cache is full. I think the code needs to check for a full cache, and provide a constructive error message. Even better, if it does not need to write to cache, I suppose.

**Comment by ericpromislow** [comment] 2020-05-18 14:41
Are there any error messages in the browser console when this happens?

Tabhunter refers to the cache only once, and that's when you explicitly reload one or more tabs.

**Comment by reikred** [comment] 2020-05-20 05:59
I just checked and I get no error messages when "blank popup" happens. I used the Alt-Shift-K console and the Console tab.

Sorry this took 2 days, I have been swamped.

**Comment by ericpromislow** [comment] 2020-05-20 14:24
Unfortunately, I don't have access to a linux box with a front-end UI right now. WFH with mac and windows laptops. Not sure when I'll get to the office.

**Comment by wsmwk** [comment] 2020-05-20 14:52
Sort of like this but transparent?
![Screen Shot 2020-05-20 at 10 51 03 AM](https://user-images.githubusercontent.com/216903/82461099-0480c880-9a88-11ea-832c-be9bc157f644.png)

**Comment by wsmwk** [comment] 2020-05-20 14:53
How does one know if the cache is full?  I have 1,129 tabs currently and never hit an error that I recall - although it can sometimes be slow :)

**Comment by ericpromislow** [comment] 2020-05-20 16:55
Can't say about the cache, but it shouldn't affect tabhunter style & perf.

**Comment by reikred** [comment] 2020-05-20 20:38
@ericpromislow @wsmwk ,

Attached is what the bug looks on my linux/X11 box. As you can see, the TabHunter "doorhanger-style" popup that hangs from the TH addon icon is empty (just a stipple-pattern outline). Note I have 3974 tabs open, as visible in the Tab Count Badge icon near the TH icon. As can also be seen, the cache(etc) at 143MB is not full.

(@wsmwk you can see the cache usage in this picture of the page about:preferences#privacy. In this case the cache (etc) usage is 143MB. Full will be when 1GB cache, which will appear as 1.XGB due to the cookies and site data on top of that. But 1GB is generally the cache size limit, at which ppoint performance will deteriorate for the browser overall as it thrashes to find out what webpage data to replace, but that is unrelated to the subject bug of the TH popup being empty).

![2020-05-20 13-22-12 Wed](https://user-images.githubusercontent.com/10853083/82494923-2c2f5b00-9a9f-11ea-8375-14a90354f19f.png)

**Comment by ericpromislow** [comment] 2020-05-20 21:04
3974 tabs… Maybe something fundamental timed out, but you should still see buttons and other widgets in the popup panel, not nothing.

**Comment by reikred** [comment] 2020-05-20 21:56
@ericpromislow it is nothing fundamental to firefox, as a tab search using the built-in tab searching function (prefix % in URL bar) works fine and instantly, as you can see from screenshot. But of course I would much rather uses TH addon than the %-search because TH is so much better!

Wild guesses: memory leak? timeout, as you said? Maybe use %-search API (if exists) under the hood in TH would help?

![2020-05-20 14-50-42 Wed](https://user-images.githubusercontent.com/10853083/82501196-b8468000-9aa9-11ea-8418-61ba9234bd4d.png)

**Comment by reikred** [comment] 2020-05-21 15:01
@ericpromislow By the way, the problems happens just as easily in another profile with 1929 tabs. After running for a while, it will stop working.

**Comment by reikred** [comment] 2020-05-21 15:13
Okay, here is an idea: How about putting a message in the popup  saying "loading and searching tabs..." BEFORE starting to do whatever function call is needed to get firefox to send you the list of tabs. That would at least give a hint as to where the problem might be. Once the list is returned, then populate the popup and overwrite the message. Should be easy for you to do, knowing the code?

**Comment by ericpromislow** [comment] 2020-05-21 15:24
I'm more concerned why none of the buttons show up in the panel -- I would expect them to appear immediately. That suggests that a "loading…" message wouldn't appear either. 

As a thought, how do other popup-based extensions fare when you have 1000s of tabs loaded? Are you using something like The Great Suspender (unfortunately Chrome-only) to suspend older tabs?

**Comment by reikred** [comment] 2020-05-21 15:42
General observation: With so much object-oriented stuff in the API, can one really tell whether the addon will draw buttons before the tab query finishes or after?

As you can see in the screenshots above I have plenty of addons. Not seen any of them not presenting the appropriate popup when pressed, and I use them frequently.

A little bit of info/debug instrumentation would go a long way to narrow down the problem.

I'm on firefox 76.0.1 (not that the version matters much), and never used the The Great Suspender.

**Comment by reikred** [comment] 2020-05-21 17:53
@ericpromislow Okay, here is an update about how well other addons are doing listing all the tabs:  With TH in the bad state, I tried the  using the addon MySessions (click on it) so that it will exercise listing all tabs. It works fine, as can be seen in the attached screenshot, BUT if I try scrolling around in the list of tabs it becomes slower and laggy, maybe 5sec wait in the current state where TH  also in infinite lag mode (although TH popup not open at the same time of course). Likewise, if I use the firefox "v" list-all-tabs widget, it is fast to appear but slow and laggy to scroll.

In another browser instance, all of TH and MySessions and list-all-tabs are fast and scroll instantly.

So, something about the underlying mechanism for "list-all-tabs" (or later traversing the list as is needed for scrolling) is not robust and degrades over time.

However, I think TH only should need to call list-all-tabs once, and should not fail completely. At worst It should just be slow and laggy like the others. So some longer timeout maybe needed somewhere?

![2020-05-21 10-38-09 Thu](https://user-images.githubusercontent.com/10853083/82589632-47f33980-9b51-11ea-91ab-b0959135e864.png)

**Comment by reikred** [comment] 2020-05-21 19:02
May be related to the following bug, which strangely has been languishing for 3 years but has activity today !!

https://bugzilla.mozilla.org/show_bug.cgi?id=1384733

**Comment by ericpromislow** [comment] 2020-05-28 17:11
I might have something...

On the family imac, various family members started running out of memory yesterday. An OOM popup said FF was using about 480 MB, but the activity monitor was showing about 8 "Firefox Web Content CP" processes each using another 1/2 Gig. Only an 8GB computer because when I bought it in January the store couldn't get extra RAM due to some virus problem in China.

But, after a full reboot and bringing up Tabhunter with about 50 tabs (it runs in the family), the popup was blank!

So I went into `about:config` and set the following:

`dom.ipc.processCount` = 1 (default 8)
`browser.tabs.remote.autostart` = false (default ?) - true on the imac, false on my laptop, which has no such problems
`browser.tabs.remote.autostart2` = false (default true)

I don't know exactly what these do. But it fixed the problem. For some weird reason my non-techie family all prefer FF to the alternatives, and I was about to give up on it. But running a single-process FF seems to have fixed that memory leak. As well as Tabhunter.

**Comment by reikred** [comment] 2020-06-05 16:42
I'm glad you have been able to observe the subject problem, too ;-). Not sure whether it has to do with multiprocess or not, it could also be that your restart after changing the parameters? Is that particular firefox instance set up to clear cache on exit? That could make all the difference.

For reference, what I found by looking up browser.tabs.remote.autostart:
https://support.mozilla.org/en-US/questions/1207724

Perhaps you can ask the family to be on the lookout for the buggy behavior and see if it comes back?

PS: The fix for that other suspect bugzilla  1384733 appears to be scheduled for firefox 78.0, maybe comes out in a few weeks?

**Comment by ericpromislow** [comment] 2020-06-30 18:14
Apparently fixed by upgrading to FF 78. Please reopen if it's still a problem

**Closed by ericpromislow** 2020-06-30 18:14 UTC

**Comment by reikred** [comment] 2021-03-01 04:36
The problem is back in firefox 86.0. Only in one of my profiles, and that proifile has 4065 tabs. It was working before I updated from firefox 84.0.

**Comment by reikred** [comment] 2021-03-04 05:23
FIX: In the three profiles where TabHunter had a blank window, changing the following about:config value from TRUE to FALSE

gfx.xrender.enabled ---> false (and restarting the browser)

fixed the problem. In profiles that were already working, the value already was FALSE. This is in ubuntu20.04 with firefox-86.0.

I basically discovered the difference between a "good" and a "bad" profile by comparing side-by-side the appearance of about:support. It was not fun but it did the job. Perhaps @ericpromislow understands why the xrender=TRUE value makes the popup fail.
