### ISSUE TITLE
Firefox performance impacted by Tabhunter CPOW

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ericpromislow/tabhunter#61] opened 2015-03-21 03:32 UTC
```
I'm running nightly builds+tabhunter a long time without problems. And still no 
problems...

but with e10s enabled, about:compartments shows signficant CPOW activity. 
 time 	        time in CPOWs 	name 
83272671μs	20168000μs	Tabhunter
or about 25%

ref: 
https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Cross_Process_O
bject_Wrappers
https://mikeconley.ca/blog/2015/02/17/on-unsafe-cpow-usage-in-firefox-desktop-an
d-why-is-my-nightly-so-sluggish-with-e10s-enabled/
```

Original issue reported on code.google.com by `wayne.m...@gmail.com` on 20 Feb 2015 at 1:36

**Comment by wsmwk** [comment] 2015-04-29 19:28
BTW, the tool to use is now about:performace

**Comment by wsmwk** [comment] 2015-08-17 21:34
As of a week ago version 42 Aurora (Developer Edition) has e10s enabled by default. https://wiki.mozilla.org/Firefox/Planning/2015-08-12 suggests that e10s may ship to the public for version 43

https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox

**Comment by ericpromislow** [comment] 2015-08-17 22:05
I've been working on it, in branch 61-add-message-managers. It's broken right now, hope to
have some time to get it working but will be busy the next 3 weeks or so.

**Comment by wsmwk** [comment] 2015-11-04 21:43
now seeing error
tabhunter getTabs  operation not possible on dead CPOW

**Comment by ericpromislow** [comment] 2015-11-04 21:47
This is still on a dev build, right?

**Comment by wsmwk** [comment] 2015-11-04 21:55
correct. currently 2015-10-19 - a few weeks gold because of some issues with newer builds.
tabhunter is 1.0.5.1

**Comment by wsmwk** [comment] 2015-11-30 01:12
> This is still on a dev build, right?

More specifically as I understand it is enabled in 
  A. the "Developer Edition" ( https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox )
  B. nightly builds (and has been enabled for users that do not have addons installed)
According to https://wiki.mozilla.org/Electrolysis#Schedule will be enabled for A/B testing late in beta 43. 

It looks like they are hoping to target release for version 45.

It is concurrently one of two addions that I have the most trouble with. The other is Treestyletabs

**Comment by morspin** [comment] 2015-11-30 02:54
Turns out I can only roll over 5 days of holidays, so I'm taking
tomorrow off, and will see what I can do.  Even if I do update
Tabhunter, Mozilla plans on deprecating XUL/XPCOM addons,
moving to the same API that Chrome uses.  I'll see what I can
accomplish tomorrow, and then "office hours" are on Tuesday
if I have any specific questions.

I'm with the vocal majority who's not happy with this roadmap.
It's like Mozilla/FF is chasing both webkit and mobile form factors,
and leaving their core constituency else behind.

**Comment by wsmwk** [comment] 2015-12-19 13:39
subjectively, performance impact seems to be a bit more severe now.
FWIW, 45 with e10s will be beta in ~5 weeks.

**Comment by morspin** [comment] 2015-12-25 06:04
Guess what I managed to get done today (almost)? Could you have a
look at the 61.1-add-message-managers branch?  It's easy to build --
pull down the code, run 'sh build.sh' (or whatever people do if they're
running that Windows thing), and then either drag-and-drop the
tabhunter-1.0.12.xpi icon onto Firefox or use the FF add-ons page to
load the add-on from the Gear menu.

It's not done yet -- I'm curious about the performance, and if it misses
any tabs when you load the dialog. It's all async, and if I got paid
to work on this I'd make it completely async, but I have other things
I needed to do.

One definite bug -- when you open a tab in a new window, Tabhunter
won't find that tab until you close Tabhunter and reopen it.

The "current tab" thing is broken.

I plan on turning text-search off as well until I get the other things above
working.

**Comment by ericpromislow** [comment] 2016-01-04 06:06
Please see https://github.com/ericpromislow/tabhunter/releases/tag/v1.0.20 and let me know if it works. Download tabhunter-1.0.20.zip, rename as tabhunter-1.0.20.xpi, drag/drop onto FF, and let me know if you run into any issues. Besides the three I'm aware of: I dropped text-search, I have to restart TH after opening a new window, and sometimes it fails to rebuild the list. The second two look like mozilla bugs, but it's hard to say.

**Comment by wsmwk** [comment] 2016-01-07 11:16
I'm running with it for a few days.  
performance of tabhunter itself is much better.
performance of Firefox - I haven't seen firefox complaining that tabhunter is slowing it up.

But I am also having issues - environment is >400 tabs:
- seeing major Firefox performance issues - unclear yet if it's caused by a newer version of firefox or a new addon (like Nimbus screen shot). 
- tabhunter stopped working - the dialog comes up but does not display list of tabs 
- error console has repeating series of the following (not sure which is the first in the sequence)

sessionTrack: updateOnTabChange exception: [Exception... "Component not initialized" nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)" location: "JS frame :: chrome://tabhunter/content/selectTabDialog.js :: this._updateList :: line 301" data: no], this._updateList@chrome://tabhunter/content/selectTabDialog.js:301:3
this.updateOnTabChange/<@chrome://tabhunter/content/selectTabDialog.js:275:17
this.dualProcessSetupFinalCallback@chrome://tabhunter/content/asyncTabCollector.js:108:8
this.dualProcessContinuationFinish@chrome://tabhunter/content/asyncTabCollector.js:85:8
this.getTabs_dualProcessContinuation@chrome://tabhunter/content/asyncTabCollector.js:126:5
this.process_docType_has_image_continuation_msg@chrome://tabhunter/content/asyncTabCollector.js:173:8

th: this.currentTabList.getRowCount not a func. id: currentTabList,node name:listbox

and also 
TH/ATC: asyncTabCollector.js - collectTabs - [Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: chrome://tabhunter/content/asyncTabCollector.js :: this.getTabs_dualProcess :: line 243"  data: no]
this.getTabs_dualProcess@chrome://tabhunter/content/asyncTabCollector.js:243:33
this.collectTabs@chrome://tabhunter/content/asyncTabCollector.js:70:4
this.updateOnTabChange@chrome://tabhunter/content/selectTabDialog.js:271:5
this.process_DOMContentLoaded@chrome://tabhunter/content/asyncTabCollector.js:36:2

**Comment by wsmwk** [comment] 2016-01-07 12:23
also spots of 
TypeError: tabContainer is undefined
and others. But performance is too poor, so I must restart

**Comment by morspin** [comment] 2016-01-07 17:05
I've seen the error messages and missing list you reported, will work on
them later.

**Comment by Tragen** [comment] 2016-01-10 01:28
I don't know if it's related but I got an error because TH was very slow.

A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: chrome://tabhunter/content/asyncTabCollector.js:169

**Comment by ericpromislow** [comment] 2016-01-10 01:50
I think I've got all those issues tackled.  Please try the enclosed zip: 
rename tabhunter-1.0.22.zip tabhunter-1.0.22.xpi
Drag/drop tabhunter-1.0.22.xpi onto firefox
Retry and (hopefully) enjoy.   Please let me know if there are any issues.
[tabhunter-1.0.22.zip](https://github.com/ericpromislow/tabhunter/files/83917/tabhunter-1.0.22.zip)

**Comment by wsmwk** [comment] 2016-01-10 03:08
Firefox j2016-01-01 nightly just gave me a "Tabhunter might be making Firefox slower". So I'll start using 1.0.22.zip.

**Comment by morspin** [comment] 2016-01-10 05:24
You can also now download 1.0.22 directly from
https://addons.mozilla.org/en-US/firefox/addon/tabhunter/

**Comment by Tragen** [comment] 2016-01-10 10:25
@wsmwk: what do I need to get the warnings. Nightlies? Or do I just have to change
browser.addon-watch.interval?

**Comment by wsmwk** [comment] 2016-01-10 11:39
for me browser.addon-watch.interval is set to default 15000

**Comment by wsmwk** [comment] 2016-01-11 15:17
tentative results, 1.0.22 is better

**Comment by ericpromislow** [comment] 2016-01-17 17:00
Should be fixed by version 1.0.27

**Closed by ericpromislow** 2016-01-17 17:00 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect

**Comment by Tragen** [comment] 2016-01-18 16:47
1.0.22 was really good. But 1.0.27 is only fast when I have done the first search and the TH is still open. It takes 20 seconds to minutes until it has processed all the tabs. I have 1450 open tabs.

**Comment by morspin** [comment] 2016-01-18 18:36
Looks like I should back out the main window-iteration change, which
replaced a standard nested loop over windows
and tabs with a series of setTimeouts.  I've noticed with around 50 tabs
that it takes about 10-20 seconds to show
the first list of tabs, and then if I reopen a window that has another 50
tabs there's another delay.  When single
tabs are added or deleted, it's fast, and the CPU usage doesn't bump up
much.  So at some point I'll back
out that change.

I think it's a given that the message cycle adds to the delay.  For every
new tab, there's no way I can
avoid sending a message to get its location and image info. To avoid
swamping the CPU I try to allow
only one of these to be in progress at any time. If a message round-trip
takes 50 msec, then
1450 * 50msec => 7 seconds. Plus there's the overhead of just gathering the
tabs, as well as
writing them to the list. Those should be negligible.

Time I start finding out just how long the message-cycle takes.

**Comment by wsmwk** [comment] 2016-01-29 18:51
1.0.22 and 1.0.27 are great for me - 600+ tabs.
Thanks!

**Comment by wsmwk** [comment] 2016-02-22 22:45
However, I do miss being able to search web page contents

**Comment by ericpromislow** [comment] 2016-02-22 22:48
Yup, I wanted it the other day. Which means one of these weekends it'll go back in.

**Comment by Tragen** [comment] 2016-02-22 22:50
As long as it is optional.
How do you do it with hundreds of tabs where tabs are only loaded when you select them?
So there is no content to search and it would be bad to have all tabs loaded because of this.

**Comment by ericpromislow** [comment] 2016-02-23 00:18
I suspect that the HTML for each tab is downloaded but hasn't been rendered. But because I took the feature out when working on #e10s I'm not sure if that's still the case.
