### ISSUE TITLE
First search after a restart very slow or never completes

### ISSUE THREAD

**Issue by toad01** [ericpromislow/tabhunter#71] opened 2017-08-30 14:09 UTC
Since updating to Firefox 55.0.3 the first search after a restart is either very slow or never completes. If the Tabhunter window is closed and then re-opened the search completes quickly.

I use this plugin frequently and find it very useful. It appears to be unique in searching multiple Firefox windows as well as tabs.

**Comment by ericpromislow** [comment] 2017-08-30 18:00
I'm working on porting the plugin to the WebExtensions, which will be the only supported API in FF 57. Hope you can hang on until then.  And I'm using FF 55.0.1 on linux, don't see this problem.

**Comment by toad01** [comment] 2017-08-31 19:54
Good to know that your updating to use WebExtensions. I can wait until then. I don't have much choice, as there is no other plugin with this functionality!

**Comment by reikred** [comment] 2017-09-08 19:42
Hi Eric,

Just wanted to fill you in on what I am experiencing. The below will be a bit rambling but please bear with me as a big fan of what TabHunter has been providing.

GREAT that you are porting to WebExtensions (although I may never use the ff 57.0/WebExtensions version of firefox  because who knows if tree-style-tabs with vertical tabs will ever be supported, and I cannot live without it.) But beware of possible performance problems, and perhaps look into how the Firefox "Awesome Bar" (see reference below) does its searches.

But back to the specific topic at hand: I do also see the same problem as toad01 in ff 55.0.2. As soon as I access Tabhunter, it uses 100% cpu and gobbles memory like crazy (and by that I mean 500MB growth on a 3GB resident set size, things like that), Yes, I am the ultimate tab hog, with 1700 tabs, but I can also report that the firefox built-in "Awesome Bar" "@ SPACE searchstring" mechanism does NOT exhibit such problems, even with 1700 tabs. The ff builtin has its own limitations, such as showing only the top 9 matches. However, I have now chosen to disable Tabhunter for the time being. As for the cause of the performance problem, I would guess that the new "contentProc" dual-process architecture (since version 54.x  I think) is the culprit. So plain multiproc/e10s worked pretty well, but the contentProc change was a a problem.

I wonder if a simple extension that provide a programmable keyboard shortcut to the "@ SPACE searchstring" interface might be a nice workaround for ff<57. Right now it is kind of clunky because you have to do the search in an existing tab, clear out the URL, and enter the "@ SPACE searchstring" each time. FF will restore the existing URL after the search is over, but the whole thing is clunky. Oops, restoring the URL suddenly stopped working. Now the @-search no longer warps to the found tab, but places the URL in the current tab. Not sure why. FAIL :). The whole point is to go to the already existing tab, not to overwrite the cuyrrent tab with something you already have cued up elsewhere.

Reference:
https://support.mozilla.org/en-US/kb/awesome-bar-search-firefox-bookmarks-history-tabs

**Comment by ericpromislow** [comment] 2017-10-09 23:58
Hope this is fixed now that Tabhunter is targeting the webextensions API. To test before the next release, use the Firefox Developers' Edition, `about:debuggin`, load a temporary addon, pull up the tabhunter `manifest.json` file, and load by either pressing `Shift-Ctrl-T` or hitting the icon, now in the upper right bar.

**Comment by ericpromislow** [comment] 2017-11-29 05:38
Should be fast enough with Tabhunter 2.* in webextension-based Firefoxes.

**Closed by ericpromislow** 2017-11-29 05:38 UTC
