### ISSUE TITLE
UI Positioning

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ericpromislow/tabhunter#56] opened 2015-03-21 03:32 UTC
```
Reproduced from issue #11:

1. The UI appears in a separate window in the corner of my screen,
requiring me to shift my focus for a few short seconds while I quickly type
my query, only to have to shift right back to the FF window after I
activate my selection.
2. Even if I move the UI to appear over my FF window, this positioning is
not remembered the next time I invoke TabHunter.

What version of the product are you using? On what operating system?
version: 1.0.5
OS: Linux (Arch, Puppy, Fedora... probably any Linux build of FireFox). You can 
grab a Fedora liveCD to confirm/test without installing.
```

Original issue reported on code.google.com by `OrbisVi...@gmail.com` on 28 May 2014 at 6:38

**Comment by wsmwk** [comment] 2015-05-28 12:38
Eric, this is a duplicate of https://github.com/ericpromislow/tabhunter/issues/12

**Comment by ericpromislow** [comment] 2017-10-10 00:02
Should be fixed now that Tabhunter is targeting the webextensions API. To test before the next release, use the Firefox Developers' Edition, `about:debuggin`, load a temporary addon, pull up the tabhunter `manifest.json` file, and load by either pressing `Shift-Ctrl-T` or hitting the icon, now in the upper right bar.

**Closed by ericpromislow** 2017-10-10 00:02 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
