### ISSUE TITLE
Tabhunter opens BEHIND other windows, cannot get it to come to the front

### ISSUE THREAD

**Issue by Anoneemouse** [ericpromislow/tabhunter#63] opened 2015-12-18 23:57 UTC
Hi, 

I've used tabhunter for a very long time and LOVE it.  Some time ago, it started opening BEHIND the firefox window(s) I had open, instead of on top.  When I select the tabunter window, it won't go to it.  If I minimize the open firefox windows, I still can't get to the tabhunter one, it doesn't show up when other windows are minimized.  So I'm totally unable to use tabhunter.  

I've tried uninstalling it and re-installing it, only to have the same problem.  Please help!  I feel like I'm browsing with one hand tied behind my back without being able to use tabhunter!

**Comment by Anoneemouse** [comment] 2015-12-18 23:58
I should also have said that when this first happened I stayed on an old version of firefox.... but today installed firefox 43, and still have the same problem.

**Comment by morspin** [comment] 2015-12-19 00:07
I'm planning on spending some quality family time getting Tabhunter ready
for the next version
of Firefox, which brings in the dual-process "electrolysis" model. So I'll
have a look around
for this problem while I'm at it.

**Comment by Anoneemouse** [comment] 2015-12-19 02:36
Thank you!!  When I found tabhunter it was like a godsend... I'm really bad
about having a huge number of tabs.  Not being able to use it drives me
buggy.  Do you need a list of add ons that I have or anything that way?  If
so, is there some way for me to create a list and not have to type them all
in by hand?   Regardless, if you can fix this I'll be eternally grateful!

Happy holidays to you and yours!

**Comment by Lister0fSmeg** [comment] 2016-02-15 08:58
It sounds like Tab Hunter [TH] is opening off screen. It shows in the Task bar but clicking it does not show the TH window. A problem is that even bring the TH window on screen, closing it down and it can still not remember the new window position as it can still open off screen. Uninstalling/reinstalling dfoes not fix it.

The only way that I found of fixing it was to go into about:config options and typing tabhunter in the search/refine bar. Then modify extensions.tabhunter.screenX and extensions.tabhunter.screenY and set values which are much smaller so that TH opens on screen. After doing that TH now opens on screen each time.

**Comment by druthers** [comment] 2016-04-17 09:20
Re: Tabhunter opens BEHIND other windows, cannot get it to come to the front

The best solution:

That problem is caused by the Tabhunter window getting lost "Off screen". To bring Tabhunter back into view, use the Windows standard 'Move Window' keyboard command:

Type Alt+Space-bar, then type 'M' (Move) -- and then try the Up/Down or Left/Right Arrow keys, to move the Tabhunter window to where you can see part of it ... and then pull Tabhunter back, by dragging it with the mouse.

Then close Tabhunter, and it will "record" its current position, and reopen there next time.

**Comment by Anoneemouse** [comment] 2017-04-06 21:26
A very belated THANK YOU to "Druthers" - that worked beautifully!  Thanks also for the response from "ListerOfSmeg" for the suggestion - before I tried the about:config method, however, I tried the suggestion by DRuthers and that seems to have worked.  Hopefully it will continue to do so.  I did go look at the x and y positions in about:config before trying it, however, and both were set at -32000.  Regardless, I now have the use of tabhunter back, which I very much appreciate!

**Comment by ericpromislow** [comment] 2017-10-10 00:00
Should be fixed now that Tabhunter is targeting the webextensions API. To test before the next release, use the Firefox Developers' Edition, `about:debuggin`, load a temporary addon, pull up the tabhunter `manifest.json` file, and load by either pressing `Shift-Ctrl-T` or hitting the icon, now in the upper right bar.

**Closed** 2017-10-10 00:12 UTC
