### ISSUE TITLE
Poor tabhunter performance all of a sudden

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ericpromislow/tabhunter#45] opened 2015-03-21 03:32 UTC
```
What steps will reproduce the problem?
1. have >= 10 FF windows open and >= 700 tabs distributed among them
2. open tabhunter (TH) window
3. enter a search term eg "google" -- performance is reasonable, FF doesn't 
thrash

4. delete the "google" string from the Pattern: text widget one char at a time. 
Note that when deleting the 2nd to last remaining char FF goes into thrashing.  
The thrashing timespan appears proportional to the total # of tabs distributed 
among the FF windows. 

on my system, when i have > 800 tabs and > 12 FF windows, the thrashing 
timespan is painfully long, and makes my FF setup essentially unusable. 

this issue began when I upgraded from FFv19 to FFv20. On FFv20, even opening 
the TH window took /forever/, and any interaction with TH took even longer (eg 
typing into the Pattern widget). So I reverted to FFv19.0.2, but note that 
although the TH window opens ok, I have the delete-entered-search-string issue 
described above. 

I wonder if there's a conflict with one of the other extensions I'm running, 
i.e. one of them updated and now I have this issue. I've tried disabling 
TabMixPlus, then MultipleTabHandler, but still had the perf issue. I don't have 
time right now to try the brute-force disable almost everything and add them 
back one-by-one technique :(

My FF setup is "usable" with so many tabs because I run BarTab which keeps the 
idle tabs unloaded, and only loads the last-active tab when a saved window is 
opened via Session Manager. it all was working really well and I depend highly 
on Tabhunter.

here's my installed active extensions:

Adblock Plus2.0.3
BarTab4.0
Cookie Monster1.1.0
DNSSEC Validator1.1.5
Ghostery2.8.3
HTTPS-Everywhere3.0.4
JSView2.0.8
Multiple Tab Handler0.7.2012020901
Nightly Tester Tools3.3
NoScript2.6.1
Session Manager0.7.9.1
Stylish1.3
Stylish-Custom0.7.7
Tabhunter1.0.2
Tab Mix Plus0.4.0.3.1
Toggle Word Wrap1.9

this is on Ubuntu 10.04 64bit, on an intel T9900-based system with 8gb memory 
and an SSD.

```

Original issue reported on code.google.com by `Jeff.Hod...@KingsMountain.com` on 22 Apr 2013 at 7:07

**Comment by wsmwk** [comment] 2015-05-28 12:29
Jeff, do you still see this problem?

I currently have 344 tabs, and I can't reproduce using current nightly build (with e10s enabled)

**Comment by ericpromislow** [comment] 2017-10-10 00:04
Should be fixed now that Tabhunter is targeting the webextensions API. To test before the next release, use the Firefox Developers' Edition, `about:debuggin`, load a temporary addon, pull up the tabhunter `manifest.json` file, and load by either pressing `Shift-Ctrl-T` or hitting the icon, now in the upper right bar.

**Closed by ericpromislow** 2017-10-10 00:04 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
